#!/bin/bash

SIM=../dineroIV

${conf:=u8b16a4}
echo "conf is $conf"

parms=$(grep "^$conf	" ../dinero-parms| cut -f2- -d'	')
echo "parms is $parms"

for c in 1 2 3 4; do
    grep ^$c mem-tr.log | cut -f2- -d' ' | $SIM $parms > cache.out.$c
done

cut -f2- -d' '  mem-tr.log | $SIM $parms > cache.out.shared

# result summary
grep Metrics -A7 cache.out.*
